Repository vtex-apps/store-graphql, pull requests merged in 2018-08, with the labels that each got.

#88 Replace http to https in item imageUrl
  CHANGELOG.md
  manifest.json
  node/resolvers/catalog/fieldsResolver.ts
Labels: bug

#94 Add enableCookies on checkout mutations
  CHANGELOG.md
  graphql/types/OrderForm.graphql
  manifest.json
  node/resolvers/checkout/index.ts
Labels: enhancement

#97 Throw specific error when the product is not found on product resolver in catalog
  CHANGELOG.md
  manifest.json
  node/resolvers/catalog/index.ts
Labels: enhancement

#95 Add initializeSession, impersonate, depersonify mutations to telemarketing app.
  CHANGELOG.md
  graphql/schema.graphql
  graphql/types/Session.graphql
  manifest.json
  node/graphql/index.ts
  node/resolvers/catalog/index.ts
  node/resolvers/checkout/paymentTokenResolver.ts
  node/resolvers/httpResolver.ts
  node/resolvers/paths.ts
  node/resolvers/profile/index.ts
  node/resolvers/session/index.ts
  node/resolvers/session/sessionResolver.ts
Labels: feature

#100 Fix syntax error in Catalog Resolver
  CHANGELOG.md
  graphql/types/Session.graphql
  manifest.json
  node/resolvers/catalog/index.ts
Labels: bug

#102 Minor refact in session resolvers and add docs.
  CHANGELOG.md
  manifest.json
  node/resolvers/session/index.ts
Labels: refact
