Repository vtex-apps/store-graphql, pull requests merged in 2019-07, with the labels that each got.

#361 Fix corporate info
  CHANGELOG.md
  node/globals.ts
  node/resolvers/profile/fieldResolvers.ts
  node/resolvers/profile/services.ts
Labels: bug

#307 Chore/oms
  CHANGELOG.md
  node/clients/checkout.ts
  node/clients/index.ts
  node/clients/oms.ts
  node/dataSources/index.ts
  node/dataSources/oms.ts
  node/globals.ts
  node/resolvers/oms/index.ts
Labels: enhancement

#350 Add siteConfigs query
  CHANGELOG.md
  graphql/schema.graphql
  graphql/types/SiteConfigs.graphql
  node/clients/index.ts
  node/clients/portal.ts
  node/resolvers/index.ts
  node/resolvers/portal/index.ts
Labels: feature

#370 Fix shipsTo
  CHANGELOG.md
  graphql/schema.graphql
  graphql/types/StoreConfigs.graphql
  node/clients/index.ts
  node/clients/logistics.ts
  node/clients/portal.ts
  node/dataSources/index.ts
  node/dataSources/logistics.ts
  node/globals.ts
  node/resolvers/logistics/PickupPoint.ts
  node/resolvers/logistics/fieldResolvers.ts
  node/resolvers/logistics/index.ts
  node/resolvers/portal/index.ts
Labels: bug
